video: fbdev: mxsfb: fix build error for dma_alloc_writecombine
Source: kernel.org
MR: 117648
Type: Integration
Disposition: Merged from git://git.kernel.org/pub/scm/linux/kernel/git/rt/linux-stable-rt.git v5.10-rt
ChangeID: fd6c33d70db9869d04358dc3196a420b9f7ff28c
Description:

Since the commit

commit 212836a9929f0c91214a8a1879e6e41be0e26a6f
Author: Christoph Hellwig <hch@lst.de>
Date:   Fri Jul 26 08:58:36 2019 +0200

    dma-mapping: remove dma_{alloc,free,mmap}_writecombine

has removed dma_alloc_writecombine interface, below build
error occured:

drivers/video/fbdev/mxsfb.c: In function ‘mxsfb_overlay_map_video_memory’:
drivers/video/fbdev/mxsfb.c:2059:19: error: implicit declaration of function ‘dma_alloc_writecombine’; did you mean ‘pgprot_writecombine’? [-Werror=implicit-function-declaration]
 2059 |  ofb->video_mem = dma_alloc_writecombine(ofb->dev,
      |                   ^~~~~~~~~~~~~~~~~~~~~~
      |                   pgprot_writecombine
drivers/video/fbdev/mxsfb.c:2059:17: warning: assignment to ‘void *’ from ‘int’ makes pointer from integer without a cast [-Wint-conversion]
 2059 |  ofb->video_mem = dma_alloc_writecombine(ofb->dev,
      |                 ^
drivers/video/fbdev/mxsfb.c: In function ‘mxsfb_overlay_exit’:
drivers/video/fbdev/mxsfb.c:2134:4: error: implicit declaration of function ‘dma_free_writecombine’; did you mean ‘pgprot_writecombine’? [-Werror=implicit-function-declaration]
 2134 |    dma_free_writecombine(ofb->dev, ofb->video_mem_size,
      |    ^~~~~~~~~~~~~~~~~~~~~
      |    pgprot_writecombine

Signed-off-by: Fancy Fang <chen.fang@nxp.com>
Signed-off-by: Corey Minyard <cminyard@mvista.com>