Fix build issue
Source: MontaVista Software, LLC
MR: 109806
Type: Defect Fix
Disposition: Local
ChangeID: 3278af648b8f5b660eb546db4437eac5a8fc75a5
Description:

error: 'ERESTART_RESTARTBLOCK' undeclared (first use in this function)
  return -ERESTART_RESTARTBLOCK;

Missed adding linux/errno.h when pushing changes to repo

Signed-off-by: Armin Kuster <akuster@mvista.com>