LF-1011-25 video: fbdev: adv7535: fix build break due to i2c_new_dummy removed
Source: kernel.org
MR: 117648
Type: Integration
Disposition: Merged from git://git.kernel.org/pub/scm/linux/kernel/git/rt/linux-stable-rt.git v5.10-rt
ChangeID: 8e70ce5d4612e663751d0b7e19f7d69c24853ea2
Description:

API changed since:
2c2f00ab1641 ("i2c: remove i2c_new_dummy() API")

../drivers/video/fbdev/mxc/adv7535.c: In function ‘adv7535_probe’:
../drivers/video/fbdev/mxc/adv7535.c:299:22: error: implicit declaration of function ‘i2c_new_dummy’ [-Werror=implicit-function-declaration]
  299 |  info->i2c_dsi_cec = i2c_new_dummy(client->adapter, addr >> 1);
      |                      ^~~~~~~~~~~~~
../drivers/video/fbdev/mxc/adv7535.c:299:20: warning: assignment to ‘struct i2c_client *’ from ‘int’ makes pointer from integer without a cast [-Wint-conversion]
  299 |  info->i2c_dsi_cec = i2c_new_dummy(client->adapter, addr >> 1);

Signed-off-by: Dong Aisheng <aisheng.dong@nxp.com>
Signed-off-by: Corey Minyard <cminyard@mvista.com>