LF-1011-17 ASoC: fsl: imx-pcm-rpmsg: drop snd_soc_pcm_lib_ioctl
Source: kernel.org
MR: 117648
Type: Integration
Disposition: Merged from git://git.kernel.org/pub/scm/linux/kernel/git/rt/linux-stable-rt.git v5.10-rt
ChangeID: 385ad92ff6a2d927aa301c9509959d7824586c6f
Description:

This ioctl was removed since:
e91f134c83b1 ("ASoC: sh: Drop superfluous ioctl PCM ops")

../sound/soc/fsl/imx-pcm-rpmsg.c:701:12: error: ‘snd_soc_pcm_lib_ioctl’ undeclared here (not in a function); did you mean ‘snd_pcm_lib_ioctl’?
  701 |  .ioctl  = snd_soc_pcm_lib_ioctl,
      |            ^~~~~~~~~~~~~~~~~~~~~
      |            snd_pcm_lib_ioctl

Signed-off-by: Dong Aisheng <aisheng.dong@nxp.com>
Signed-off-by: Corey Minyard <cminyard@mvista.com>