rbtree: don't include the rcu header
Source: kernel.org
MR: 102725
Type: Integration
Disposition: Merged from git://git.kernel.org/pub/scm/linux/kernel/git/rt/linux-rt-devel.git linux-5.4.y-rt
ChangeID: 04ce694e75a17c02586fdec53c7f9031e897ce5a
Description:

The RCU header pulls in spinlock.h and fails due not yet defined types:

|In file included from include/linux/spinlock.h:275:0,
|                 from include/linux/rcupdate.h:38,
|                 from include/linux/rbtree.h:34,
|                 from include/linux/rtmutex.h:17,
|                 from include/linux/spinlock_types.h:18,
|                 from kernel/bounds.c:13:
|include/linux/rwlock_rt.h:16:38: error: unknown type name ‘rwlock_t’
| extern void __lockfunc rt_write_lock(rwlock_t *rwlock);
|                                      ^

This patch moves the required RCU function from the rcupdate.h header file into
a new header file which can be included by both users.

Signed-off-by: Sebastian Andrzej Siewior <bigeasy@linutronix.de>
Signed-off-by: Corey Minyard <cminyard@mvista.com>