LF-1162-3: clk: imx: imx8mm: add back required clk.h headfile
Source: kernel.org
MR: 117648
Type: Integration
Disposition: Merged from git://git.kernel.org/pub/scm/linux/kernel/git/rt/linux-stable-rt.git v5.10-rt
ChangeID: f740c413c2374e5cebd78b65f1483d01fbd347f6
Description:

Otherwise meet below build break:
../drivers/clk/imx/clk-imx8mm.c: In function ‘imx_clk_init_on’:
../drivers/clk/imx/clk-imx8mm.c:313:9: error: implicit declaration of function ‘clk_prepare_enable’ [-Werror=implicit-function-declaration]
  313 |   ret = clk_prepare_enable(clks[array[i]]->clk);
      |         ^~~~~~~~~~~~~~~~~~
  AR      drivers/clk/mvebu/built-in.a

Signed-off-by: Dong Aisheng <aisheng.dong@nxp.com>
Signed-off-by: Corey Minyard <cminyard@mvista.com>