Ftrace: Fix improper usage of __trace_stack() function.
Source: MontaVista Software, LLC
MR: 119674
Type: Enhancement
Disposition: Needs submitting to linux-stable-rt
ChangeID: 2d8425ecc07640027d3e855fee2af8d9dc63b4d9
Description:

When trying to compile "kernel/trace/trace_events_trigger.c" file
observed the following compile error:

kernel/trace/trace_events_trigger.c: In function ‘stacktrace_trigger’:
kernel/trace/trace_events_trigger.c:1227:3: error: too many arguments to function ‘__trace_stack’
 1227 |   __trace_stack(file->tr, flags, STACK_SKIP, preempt_count());
      |   ^~~~~~~~~~~~~
In file included from kernel/trace/trace_events_trigger.c:15:
kernel/trace/trace.h:826:6: note: declared here
  826 | void __trace_stack(struct trace_array *tr, unsigned int trace_ctx, int skip);
      |      ^~~~~~~~~~~~~
make[2]: *** [scripts/Makefile.build:280: kernel/trace/trace_events_trigger.o] Error 1
make[2]: *** Waiting for unfinished jobs....

Fix the usage of __trace_stack() as per the function defintion.

Fixes: 5e8446e3820c ("tracing: Dump stacktrace trigger to the corresponding instance")
Signed-off-by: Anand Je Sypureddy <anandje@mvista.com>
Acked-by: Corey Minyard <cminyard@mvista.com>
Signed-off-by: Corey Minyard <cminyard@mvista.com>