ASoC: SOF: imx8m: Fix compilation error
Source: kernel.org
MR: 117648
Type: Integration
Disposition: Merged from git://git.kernel.org/pub/scm/linux/kernel/git/rt/linux-stable-rt.git v5.10-rt
ChangeID: 232005c362c03c22c380309639872e6120c25fa0
Description:

sound/soc/sof/imx/imx8m.c: In function imx8m_reset:

sound/soc/sof/imx/imx8m.c:240:25: error: struct imx8m_priv has no
member named regmap_audiomixâ

  240: regmap_update_bits(priv->regmap_audiomix, AudioDSP_REG2,

We changed in the last moment the filed for audiomix regmap
but did not update all over the places.

Signed-off-by: Daniel Baluta <daniel.baluta@nxp.com>
Signed-off-by: Corey Minyard <cminyard@mvista.com>