media: hdr-ctrls: Add a missing include
Source: Xilinx
MR: 117648
Type: Integration
Disposition: Merged from https://github.com/Xilinx/linux-xlnx.git xlnx_rebase_v5.10
ChangeID: 4eac6fb0cacadbc3ba991e5a5967c05954c7c33f
Description:

The header has data types that have to be included from
types.h.

>> include/media/hdr-ctrls.h:59:2: error: unknown type name '__u8'
      59 |  __u8 eotf;
         |  ^~~~
...

Reported-by: kernel test robot <lkp@intel.com>
Signed-off-by: Hyun Kwon <hyun.kwon@xilinx.com>
Reviewed-by: Dylan Yip <dylan.yip@xilinx.com>
State: pending

Signed-off-by: Corey Minyard <cminyard@mvista.com>