MLK-21985-3 vpu: windsor: b0: fix build for next 20190607 upgrade
Source: kernel.org
MR: 117648
Type: Integration
Disposition: Merged from git://git.kernel.org/pub/scm/linux/kernel/git/rt/linux-stable-rt.git v5.10-rt
ChangeID: fe3a9840ee1bcf594d7f2987c3bdebfb2e76db07
Description:

Due to below commit:
7e98b7b542a4 ("media: v4l2: Get rid of ->vidioc_enum_fmt_vid_{cap, out}_mplane")

../drivers/mxc/vpu_windsor/vpu_encoder_b0.c:1586:2: error: unknown field ‘vidioc_enum_fmt_vid_cap_mplane’ specified in initializer
  .vidioc_enum_fmt_vid_cap_mplane = vpu_enc_v4l2_ioctl_enum_fmt_vid_cap_mplane,
  ^
../drivers/mxc/vpu_windsor/vpu_encoder_b0.c:1587:2: error: unknown field ‘vidioc_enum_fmt_vid_out_mplane’ specified in initializer
  .vidioc_enum_fmt_vid_out_mplane = vpu_enc_v4l2_ioctl_enum_fmt_vid_out_mplane,
  ^
../scripts/Makefile.build:278: recipe for target 'drivers/mxc/vpu_windsor/vpu_encoder_b0.o' failed
make[4]: *** [drivers/mxc/vpu_windsor/vpu_encoder_b0.o] Error 1

Signed-off-by: Dong Aisheng <aisheng.dong@nxp.com>
Signed-off-by: Corey Minyard <cminyard@mvista.com>