dma-mapping: add a dma_addressing_limited helper
Source: https://git.kernel.org/
MR: 298332
Type: Security Fix
Disposition: Backport from v5.3-rc1~8^2~2
ChangeID: b866455423e040813f113d8b87e8297778ee2014
Description:

Backport the missing dependency patch for CVE-2023-52762 to prevent build failure
caused by an undefined reference to dma_addressing_limited(dev), which triggers an
implicit function declaration error during compilation.

This helper returns if the device has issues addressing all present
memory in the system.

Signed-off-by: Christoph Hellwig <hch@lst.de>
Signed-off-by: E V Ravi <reluri@mvista.com>
Signed-off-by: Armin Kuster <akuster@mvista.com>