drm: xlnx: mixer: Fix linking failure for ARCH arm
Source: Xilinx
MR: 117648
Type: Integration
Disposition: Merged from https://github.com/Xilinx/linux-xlnx.git xlnx_rebase_v5.10
ChangeID: 326edc4fb395d416caa43affa0c760b222819cfb
Description:

The kernel fails to build on 32-bit arm architecture when Video Mixer
driver is enabled due to unsupported modulo operations in 32 bit mode.
The error shown is "undefined reference to `__aeabi_uldivmod'".
This is fixed by changing the data type of luma and chroma address to
dma_addr_t instead of u64.

Signed-off-by: Vishal Sagar <vishal.sagar@xilinx.com>
Reviewed-by: Hyun Kwon <hyun.kwon@xilinx.com>
Signed-off-by: Michal Simek <michal.simek@xilinx.com>
State: pending

Signed-off-by: Corey Minyard <cminyard@mvista.com>