LF-1162-7: ASoC: sof: imx8: drop incorrect suspend function definition
Source: kernel.org
MR: 117648
Type: Integration
Disposition: Merged from git://git.kernel.org/pub/scm/linux/kernel/git/rt/linux-stable-rt.git v5.10-rt
ChangeID: db77bdcf57074ed18999c2436835d876d74be4f9
Description:

Suspend() prototyle was changed since:
61e285caf40f ("ASoC: SOF: Move DSP power state transitions to platform-specific ops")

So we met below build break:
../sound/soc/sof/imx/imx8.c:425:14: error: initialization of ‘int (*)(struct snd_sof_dev *, u32)’ {aka ‘int (*)(struct snd_sof_dev *, unsigned int)’} from incompatible pointer type ‘int (*)(struct snd_sof_dev *)’ [-Werror=incompatible-pointer-types]
  425 |  .suspend  = imx8_dsp_suspend,
      |              ^~~~~~~~~~~~~~~~

Signed-off-by: Dong Aisheng <aisheng.dong@nxp.com>
Signed-off-by: Corey Minyard <cminyard@mvista.com>