net: stmmac: skip only stmmac_ptp_register when resume from suspend
Source: kernel.org
MR: 127545
Type: Integration
Disposition: Local
ChangeID: 0735e639f129dff455aeb91da291f5c578cc33db
Description:

When resume from suspend, besides skipping PTP registration, it also
skipping PTP HW initialization. This could cause PTP clock not able to
operate properly when resume from suspend.

To fix this, only stmmac_ptp_register() is skipped when resume from
suspend.

Fixes: fe1319291150 ("stmmac: Don't init ptp again when resume from suspend/hibernation")

NOTE :
This patch should have been pulled prior to previous commit
"f4c7d8948e866918d61493264dbbd67e45ef2bda". Due to which we get below build error
"stmmac_main.c:2870:13: error: 'ptp_register' undeclared (first use in this function)"
So pull now and fix the merge conflict.

Also there is a missing of header file inclusion from previoius commit
"f4c7d8948e866918d61493264dbbd67e45ef2bda" which leads to a below build error
"stmmac_platform.c:786:23: error: implicit declaration of function'pm_runtime_force_resume'"
So add the header file "pm_runtime.h".

Cc: <stable@vger.kernel.org> # 5.15.x
Signed-off-by: Mohammad Athari Bin Ismail <mohammad.athari.ismail@intel.com>
Signed-off-by: David S. Miller <davem@davemloft.net>
Signed-off-by: A. Niyas Ahamed Mydeen <nmydeen@mvista.com>
Reviewed-by: Corey Minyard <cminyard@mvista.com>
Signed-off-by: Corey Minyard <cminyard@mvista.com>