LF-1162-6: clk: imx: imx8mq: add back required clk.h headfile
Source: kernel.org
MR: 117648
Type: Integration
Disposition: Merged from git://git.kernel.org/pub/scm/linux/kernel/git/rt/linux-stable-rt.git v5.10-rt
ChangeID: 2e1ba58f369cd1bca25ef6ce315155a3470a8e61
Description:

Otherwise meet below build break:
  CC      drivers/char/mem.o
../drivers/clk/imx/clk-imx8mq.c: In function ‘imx_clk_init_on’:
../drivers/clk/imx/clk-imx8mq.c:296:9: error: implicit declaration of function ‘clk_prepare_enable’ [-Werror=implicit-function-declaration]
  296 |   ret = clk_prepare_enable(clks[array[i]]->clk);

Signed-off-by: Dong Aisheng <aisheng.dong@nxp.com>
Signed-off-by: Corey Minyard <cminyard@mvista.com>