include: uapi: xlnxsync: fix hdrtest failure due to unknown type name
Source: Xilinx
MR: 117648
Type: Integration
Disposition: Merged from https://github.com/Xilinx/linux-xlnx.git xlnx_rebase_v5.10
ChangeID: ba6350f8e5d5c9866b0de3b1def5e279d12ab825
Description:

When enabling CONFIG_UAPI_HEADER_TEST, there will be compile error as
below:

In file included from <command-line>:32:
./usr/include/linux/xlnxsync.h:37:2: error: unknown type name ‘u8’
   37 |  u8 prod_sync : 1;
      |  ^~

There is no u8/u16/u32/u64/bool definition in uapi headers. So we need
use __u8/__u16/__u32/__u64 which defined in include/uapi/linux/types.h.

Signed-off-by: Quanyang Wang <quanyang.wang@windriver.com>
State: pending

Signed-off-by: Corey Minyard <cminyard@mvista.com>