LF-1197-1 clk: imx: remove the unused IMX7D_PXP_CLK definition
Source: kernel.org
MR: 117648
Type: Integration
Disposition: Merged from git://git.kernel.org/pub/scm/linux/kernel/git/rt/linux-stable-rt.git v5.10-rt
ChangeID: 9e537a755ea0ece2f98c9568ebeaf0730898eac9
Description:

../drivers/clk/imx/clk-imx7d.c:794:6: error: ‘IMX7D_PXP_CLK’ undeclared (first use in this function); did you mean ‘IMX7D_OCOTP_CLK’?
  794 |  hws[IMX7D_PXP_CLK] = imx_clk_hw_gate4("pxp_clk", "main_axi_root_clk", base + 0x44c0, 0);
      |      ^~~~~~~~~~~~~

Signed-off-by: Dong Aisheng <aisheng.dong@nxp.com>
Signed-off-by: Corey Minyard <cminyard@mvista.com>