LF-4784 soc: imx: Fix build break for 32bit nosmp config
Source: kernel.org
MR: 117648
Type: Integration
Disposition: Merged from git://git.kernel.org/pub/scm/linux/kernel/git/rt/linux-stable-rt.git v5.10-rt
ChangeID: 9382a451edaddfe93a3c16a214efe279858ec989
Description:

Fix below build break when using 32bit ARM & NOSMP config

  CC      drivers/soc/imx/rpmsg_life_cycle.o
drivers/soc/imx/rpmsg_life_cycle.c: In function 'rpmsg_life_cycle_notifier':
drivers/soc/imx/rpmsg_life_cycle.c:49:9: error: implicit declaration of
function 'remove_cpu' [-Werror=implicit-function-declaration]
   49 |   ret = remove_cpu(cpu);
      |         ^~~~~~~~~~
cc1: some warnings being treated as errors

Fixes: d32b5fb023d3 ("LF-4707 soc: imx: Add rpmsg life cycle support on imx8ulp")

Signed-off-by: Jacky Bai <ping.bai@nxp.com>
Reviewed-by: Peng Fan <peng.fan@nxp.com>
Signed-off-by: Corey Minyard <cminyard@mvista.com>