imx: mlb: Replace ACCESS_ONCE with READ_ONCE
Source: kernel.org
MR: 117648
Type: Integration
Disposition: Merged from git://git.kernel.org/pub/scm/linux/kernel/git/rt/linux-stable-rt.git v5.10-rt
ChangeID: 988573989425deaa25ae9bcbcdc4eddfb428c71c
Description:

As per commit 6aa7de059173 ("locking/atomics: COCCINELLE/treewide: Convert
trivial ACCESS_ONCE() patterns to READ_ONCE()/WRITE_ONCE()"), replace
ACCESS_ONCE with READ_ONCE to fix the compilation errors.

drivers/mxc/mlb/mxc_mlb.c: In function ‘mlb_rx_isr’:
drivers/mxc/mlb/mxc_mlb.c:1664:9: error: implicit declaration of function ‘ACCESS_ONCE’; did you mean ‘READ_ONCE’? [-Werror=implicit-function-declaration]
  tail = ACCESS_ONCE(rx_rbuf->tail);
         ^~~~~~~~~~~
         READ_ONCE
  CC      drivers/of/of_mdio.o

Signed-off-by: Vipul Kumar <vipul_kumar@mentor.com>
Signed-off-by: Corey Minyard <cminyard@mvista.com>