netfilter: nftables: add nft_parse_register_store() and use it
Source: kernel.org
MR: 157711
Type: Security Fix
Disposition: Backport from v4.19
ChangeID: f8334ec79de9012a817bf27432a3e7cec4b645af
Description:

[ 345023b0db315648ccc3c1a36aee88304a8b4d91 ]

This new function combines the netlink register attribute parser
and the store validation function.

This update requires to replace:

        enum nft_registers      dreg:8;

in many of the expression private areas otherwise compiler complains
with:

        error: cannot take address of bit-field ‘dreg’

when passing the register field as reference.

Signed-off-by: Pablo Neira Ayuso <pablo@netfilter.org>
Signed-off-by: Sasha Levin <sashal@kernel.org>
Signed-off-by: Hardik Gohil <hgohil@mvista.com>
Signed-off-by: Corey Minyard <cminyard@mvista.com>