LF-1197-2 gpu: drm: imx: ipuv3: remove drmP.h
Source: kernel.org
MR: 117648
Type: Integration
Disposition: Merged from git://git.kernel.org/pub/scm/linux/kernel/git/rt/linux-stable-rt.git v5.10-rt
ChangeID: 27a57d9aa3fd1b324e84af3042be452a2d3f545b
Description:

API changes:
4e98f871bcff ("drm: delete drmP.h + drm_os_linux.h")

drivers/gpu/drm/imx/ipuv3/ipuv3-kms.c:15:10: fatal error: drm/drmP.h: No such file or directory
   15 | #include <drm/drmP.h>

Signed-off-by: Dong Aisheng <aisheng.dong@nxp.com>
Signed-off-by: Corey Minyard <cminyard@mvista.com>