staging: fsl_qbman: include new header file linux/dma-mapping.h
Source: kernel.org
MR: 117648
Type: Integration
Disposition: Merged from git://git.kernel.org/pub/scm/linux/kernel/git/rt/linux-stable-rt.git v5.10-rt
ChangeID: 4525effc5cf8bbe117c19cb7f3b7ad1bc6cee1d9
Description:

New headfile introduced from:
0a0f0d8be76d ("dma-mapping: split <linux/dma-mapping.h>")

Including it to fix the build issue below:

drivers/staging/fsl_qbman/qman_high.c: In function ‘qman_create_portal’:
drivers/staging/fsl_qbman/qman_high.c:687:2: error: implicit declaration of function ‘arch_setup_dma_ops’; did you mean ‘arch_setup_new_exec’? [-Werror=implicit-function-declaration]
  arch_setup_dma_ops(&portal->pdev->dev, 0, 0, NULL, true);
  ^~~~~~~~~~~~~~~~~~
  arch_setup_new_exec

Signed-off-by: Li Yang <leoyang.li@nxp.com>
Signed-off-by: Corey Minyard <cminyard@mvista.com>