Revert "arm64: dts: imx8mn: Add LPDDR4 EVK pmic support"
Source: kernel.org
MR: 117648
Type: Integration
Disposition: Merged from git://git.kernel.org/pub/scm/linux/kernel/git/rt/linux-stable-rt.git v5.10-rt
ChangeID: 170d11c8166b2ba2c7be102b52cce4d5e461ffdc
Description:

This reverts commit 000fdfcf131133f4c618dbf6bf3a2587661649c6.
Revert this patch to fix the build below break:

arch/arm64/boot/dts/freescale/imx8mn-evk.dts:235.24-239.4: ERROR (duplicate_label):
/soc@0/bus@30000000/pinctrl@30330000/pmicirq: Duplicate label 'pinctrl_pmic' on
/soc@0/bus@30000000/pinctrl@30330000/pmicirq and /soc@0/bus@30000000/pinctrl@30330000/pmicirqgrp

arch/arm64/boot/dts/freescale/imx8mn-evk.dts:117.19-231.4: ERROR (duplicate_label):
/soc@0/bus@30800000/i2c@30a20000/pca9450@25: Duplicate label 'pmic' on
/soc@0/bus@30800000/i2c@30a20000/pca9450@25 and /soc@0/bus@30800000/i2c@30a20000/pmic@25

ERROR: Input tree has errors, aborting (use -f to force output)

scripts/Makefile.lib:326: recipe for target 'arch/arm64/boot/dts/freescale/imx8mn-evk.dtb' failed

Signed-off-by: Jacky Bai <ping.bai@nxp.com>
Signed-off-by: Corey Minyard <cminyard@mvista.com>