LF-1162-2 Revert "dmaengine: imx-sdma: fix context cache"
Source: kernel.org
MR: 117648
Type: Integration
Disposition: Merged from git://git.kernel.org/pub/scm/linux/kernel/git/rt/linux-stable-rt.git v5.10-rt
ChangeID: ffbae8ed9852915e1f8ac197bad1717c2dbe6438
Description:

This reverts commit d288bddd8374e0a043ac9dde64a1ae6a09411d74.

This patch is invalid since local commit:
a03180986b79 ("Revert "dmaengine: imx-sdma: refine to load context only once"")

Otherwise, met build break as follows:
../drivers/dma/imx-sdma.c: In function ‘sdma_free_chan_resources’:
../drivers/dma/imx-sdma.c:1533:7: error: ‘struct sdma_channel’ has no member named ‘context_loaded’
 1533 |  sdmac->context_loaded = false;
      |       ^~

Module onwer could follow for a fine tuned solution.

Signed-off-by: Dong Aisheng <aisheng.dong@nxp.com>
Signed-off-by: Corey Minyard <cminyard@mvista.com>