netfilter: nftables: add nft_parse_register_load() and use it
Source: kernel.org
MR: 157711
Type: Security Fix
Disposition: Backport from v4.19
ChangeID: f341e6f0da0ef35478e2a637e3e0968d6774b836
Description:

[ 4f16d25c68ec844299a4df6ecbb0234eaf88a935 ]

This new function combines the netlink register attribute parser
and the load validation function.

This update requires to replace:

	enum nft_registers      sreg:8;

in many of the expression private areas otherwise compiler complains
with:

	error: cannot take address of bit-field ‘sreg’

when passing the register field as reference.

Signed-off-by: Pablo Neira Ayuso <pablo@netfilter.org>
Signed-off-by: Sasha Levin <sashal@kernel.org>
Signed-off-by: Hardik Gohil <hgohil@mvista.com>
Signed-off-by: Corey Minyard <cminyard@mvista.com>